### ISSUE TITLE
Sorter kommuner etter navn

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMapi#10]
Ved kalkulering av kommuner i mønstringen bør denne sorteres alfabetisk for videre loop av kommune-arrayet senere (ved utlisting er det mest fornuftig å få dette sortert alfabetisk, og ikke i tilfeldig rekkefølge)

**Comment by AsgeirSH** [comment]
Marius' patented "Fix and Forget" (tm)
