### ISSUE TITLE
Oppgrader database-charset

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMapi#49]
Bruk `utf8mb4_danish_ci` fordi `utf8mb4_unicode_ci` (eller `utf8mb4_general_ci`) klarer å sortere nordiske karakterer riktig  (å=a)

**Comment by AsgeirSH** [comment]
Fullført uten issues for alt unntatt:
- ukm_navn - Duplicate key for HAAKON / HÅKON
- ukm_standalone_video - Key too long, maximum 1000 bytes.

**Comment by mariusmandal** [comment]
Vi støtter nå bare Håkon (ikke Haakon), og tabellen er fixed :) 
ukm_standalone_video henger igjen i latin1, så den får et eget issue for en annen dag

**Comment by mariusmandal** [comment]
Løst med script eller manual labour @AsgeirSH ? Må jo få disse endringene over i dev etter hvert også..

**Comment by AsgeirSH** [comment]
Semi-semi, men tror vi like gjerne bør eksportere database-strukturen fra prod når vi starter på nytt dev-oppsett.
