### ISSUE TITLE
DB: ukm_standalone_video må forlate latin1 til fordel for utf8mb4

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMapi#51]
Det må skrives en SQL-spørring for å endre charset. Denne må lagres i en egen fil under https://github.com/UKMNorge/UKMapi og `_DB-migration`.
Når den funker, må den også kjøres på prod-server (@mariusmandal kan gjøre dette)

**Comment by mariusmandal** [comment]
Denne må kanskje innom binær-data for å fungere tilstrekkelig?

**Comment by Jimtrim** [comment]
Antar dere kjører på en eller annen InnoDB eller MyISAM-kompatibel databqse (MySQL, MariaDB, Postgres). Da skal det finnes ALTER TABLE/COLUMN-spørringer for sånt.

Merk at noen tegn kan bli ødelagt i konverteringer, som oftesr snakk om Emoji

**Comment by mariusmandal** [comment]
Per i dag er det ikke emoji-support i denne tabellen @Jimtrim, som er noe av det vi ønsker å få inn med nytt charset (selv om vi ikke ønsker emojis).
Vi har eksempel på slike alter table-queries i https://github.com/UKMNorge/UKMapi/tree/master/_DB-migration mener jeg, men er litt usikker.
Fordi vi har lagret utf8-data i en latin1-tabell i lang tid ( 🤦🏼‍♂️), må kolonnene først konverteres til binærdata-felt, og deretter konverteres til utf8mb4 danish. Da unngår vi at databasen prøver å outsmarte oss ved å konvertere data fra latin1 til utf8 (som gir superkrøll når det ligger utf8-data der).

Note to @mariusmandal (aka self): Pass på å duplisere tabellen med innhold før konvertering i prod, i tilfelle vi får feil-konverteringer som ikke oppdages med en gang.

**Comment by Jimtrim** [comment]
Har sett på tidligere løsning, oppdatert denne for ukm_standalone_video, men får feil tegn i manuell sjekk av data etterpå. 
[encoding-dbfix.zip](https://github.com/UKMNorge/UKMapi/files/4025915/encoding-dbfix.zip)

**Comment by mariusmandal** [comment]
Vi bruker ikke lengre denne tabellen 🎉
