### ISSUE TITLE
GITHUB: Konfigurer auto-slett etter merge

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMapi#53]
Ikke akkurat et UKMapi-issue, men det er det mest logiske repoet vi har hvor denne kan puttes atm.
https://help.github.com/en/github/administering-a-repository/managing-the-automatic-deletion-of-branches

**Comment by AsgeirSH** [comment]
Du har jo også muligheten til å gjøre det når man merger pull requests - det er en egen knapp der for det :)
