### ISSUE TITLE
Arrangement::getInnslagTyper() burde sortere titlene bedre.

### ISSUE THREAD

**Issue by AsgeirSH** [UKMNorge/UKMapi#72]

**Comment by mariusmandal** [comment]
@AsgeirSH bruker koden `->getAll()` der du fikk rar sortering? Hvis man itererer uten å bruke getAll er de nemlig ikke sortert :/

**Comment by AsgeirSH** [comment]
Dette var i Delta -> type.html.twig, som bruker `arrangement.getInnslagTyper()` @mariusmandal

**Comment by AsgeirSH** [comment]
Fixed når man bruker getAll() - closing.
