### ISSUE TITLE
InnslagType::erJobbeMed() for alle uten titler blir fort feil for f.eks Dataspill

### ISSUE THREAD

**Issue by AsgeirSH** [UKMNorge/UKMapi#73]
Vi må ha en bedre måte å hente ut og lable disse, spesielt i Delta. 

Nå looper vi først igjennom alle `type in getInnslagTyper() if type.harTitler()`, deretter `type.erJobbeMed()` litt lenger ned. 

https://github.com/UKMNorge/UKMdelta/blob/innslagtype-yaml/src/UKMNorge/DeltaBundle/Resources/views/Innslag/type.html.twig#L32

**Comment by AsgeirSH** [comment]
Løses med å legge inn et kategori-felt i yml-config, som kan enten være "jobbe" eller "vise". Legg også til et "harBeskrivelse"-flagg. I Delta, dersom en type ikke har noen av "harXXX"-flaggene skal de bli påmeldt direkte.

**Comment by mariusmandal** [comment]
Måtte fikse denne for å komme videre med UKMdeltakere @AsgeirSH  :)
