### ISSUE TITLE
Ny deltakerkategori: Cosplay

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMapi#74]
Skal være type gruppe, og utover det mangler stort sett alt av min innsikt i deltakergrenens språk, definisjoner og muligheter.
Heter funksjonen karakter?
Trenger ikke tekniske behov eller titler, men kan kanskje ha beskrivelse?

**Comment by AsgeirSH** [comment]
Lurte på om denne burde ha ca samme ekstra-valg som Litteratur: Vil du vise fram på scenen? Da blir det i så fall en tittel også, så tar ikke tak i dette nå i første omgang.

**Comment by AsgeirSH** [comment]
Fixed by 876db14d13
