### ISSUE TITLE
Ikke prøv å tagge kontaktpersoner i .dev?

### ISSUE THREAD

**Issue by AsgeirSH** [UKMNorge/UKMapi#79]
Enten i Mailchimp API eller i UKMnettverket?

**Comment by AsgeirSH** [comment]
Meh, don't bother. Vil ikke blokkere det i Mailchimp API siden vi kjører PHPUnit for å teste biblioteket.

**Comment by mariusmandal** [comment]
@AsgeirSH jeg luka ut denne fra UKMnettverket jeg :)
