### ISSUE TITLE
Ny epost-klasse bør kaste Exception dersom Svar_Til mangler

### ISSUE THREAD

**Issue by AsgeirSH** [UKMNorge/UKMapi#84]
Evt ikke kreve at den er satt og heller defaulte til avsender - innspill @mariusmandal ?

Får pdd. den mer kryptiske 
```
FatalThrowableError in Epost.php line 198:
Call to a member function getEpost() on null
```

**Comment by mariusmandal** [comment]
Hva tror du om denne @AsgeirSH ?
if ($mottaker->getEpost() == UKM_MAIL_REPLY && ($this->svar_til !== null && $this->svar_til->getEpost() == UKM_MAIL_REPLY)) {

https://github.com/UKMNorge/UKMapi/blob/master/Kommunikasjon/Epost.php#L197

**Comment by AsgeirSH** [comment]
Liker den om det kun er der vi bruker svar_til? @mariusmandal

**Comment by mariusmandal** [comment]
Skal gjøre et søk i klassen i morra, og pushe den ut @AsgeirSH. Takk!
