### ISSUE TITLE
Namespace avis.class

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMapi#90]
Begge avis-klassene må namespaces. 
Brukes i dag av
- [x] https://github.com/UKMNorge/UKMpr
- [ ] https://github.com/UKMNorge/UKMrapporter
- [x] https://github.com/UKMNorge/UKMpressemelding

...som alle er ute av drift

**Comment by AsgeirSH** [comment]
UKMpr blir også inkludert i UKMwp_dashboard på noe vis?
![Screenshot 2020-01-08 at 09 52 32](https://user-images.githubusercontent.com/1831028/71963800-b49e1500-31fc-11ea-9cc8-763fa9d13d93.png)

@mariusmandal
