### ISSUE TITLE
Oppgrader related.class til APIv3-standard

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMapi#91]
Denne påvirker UKMbilder og UKMvideo i stor grad.

Målet må være å bruke `$innslag->getBilder()`, `$innslag->getFilmer()` og `$innslag->getArtikler()` i koden, ikke `related`-klassen.

**Comment by mariusmandal** [comment]
`Bilder::Write-klassen` (og en ikke-opprettet `Artikkel::Write`) bør vel begge extende en flyttet `related.class`, slik at ikke lagre-koden dupliseres. Deretter kan related.class i den form den finnes i dag fases ut over alt.

**Comment by AsgeirSH** [comment]
Er ikke mye av denne funksjonaliteten håndtert av `\Innslag\Media\Bilder\Bilde` etc-klassene?

https://github.com/UKMNorge/UKMapi/blob/187c7adb4f8e18ca4436ddcd83c5a4b14b4b154c/Innslag/Media/Bilder/Bilde.php

**Comment by mariusmandal** [comment]
Jo, veldig mye er håndtert av det @AsgeirSH , og nå når UKM-TV også blir flytta ut er det strengt tatt bare artikler igjen 🎉 

Så når vi får flytta artikler, så kan vi lukke denne uten å gjøre noe mer! 🙌🏼

**Comment by mariusmandal** [comment]
Tatt inn i feature request system
